export enum CustomerSearchTypeEnum {
  ALL = 'ALL',
  SELF = 'SELF',
  DEPARTMENT = 'DEPARTMENT',
  CUSTOMER_COLLABORATION = 'CUSTOMER_COLLABORATION',
  CUSTOMER_TRANSITION = 'CUSTOMER_TRANSITION',
  OPPORTUNITY_TRANSITION = 'OPPORTUNITY_TRANSITION',
  SELF_QUOTATION = 'SELF_QUOTATION',
}

export enum CustomerFollowPlanStatusEnum {
  ALL = 'ALL',
  PREPARED = 'PREPARED',
  UNDERWAY = 'UNDERWAY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
